/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MontarTreinoRouteImport } from './routes/montar-treino'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComparacoesRouteImport } from './routes/comparacoes'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AnamnesesRouteImport } from './routes/anamneses'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosIndexRouteImport } from './routes/alunos.index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AlunosStudentIdRouteImport } from './routes/alunos.$studentId'
import { Route as AlunoProgressoRouteImport } from './routes/aluno.progresso'
import { Route as AlunoComparacaoRouteImport } from './routes/aluno.comparacao'
import { Route as AlunoAnamneseRouteImport } from './routes/aluno.anamnese'
import { Route as AlunoAgendaRouteImport } from './routes/aluno.agenda'

const MontarTreinoRoute = MontarTreinoRouteImport.update({
  id: '/montar-treino',
  path: '/montar-treino',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparacoesRoute = ComparacoesRouteImport.update({
  id: '/comparacoes',
  path: '/comparacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamnesesRoute = AnamnesesRouteImport.update({
  id: '/anamneses',
  path: '/anamneses',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunosRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunosStudentIdRoute = AlunosStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AlunosRoute,
} as any)
const AlunoProgressoRoute = AlunoProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoComparacaoRoute = AlunoComparacaoRouteImport.update({
  id: '/comparacao',
  path: '/comparacao',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAnamneseRoute = AlunoAnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AlunoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/alunos': typeof AlunosRouteWithChildren
  '/anamneses': typeof AnamnesesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comparacoes': typeof ComparacoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/montar-treino': typeof MontarTreinoRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/anamnese': typeof AlunoAnamneseRoute
  '/aluno/comparacao': typeof AlunoComparacaoRoute
  '/aluno/progresso': typeof AlunoProgressoRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/aluno/': typeof AlunoIndexRoute
  '/alunos/': typeof AlunosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamneses': typeof AnamnesesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comparacoes': typeof ComparacoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/montar-treino': typeof MontarTreinoRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/anamnese': typeof AlunoAnamneseRoute
  '/aluno/comparacao': typeof AlunoComparacaoRoute
  '/aluno/progresso': typeof AlunoProgressoRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/aluno': typeof AlunoIndexRoute
  '/alunos': typeof AlunosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/alunos': typeof AlunosRouteWithChildren
  '/anamneses': typeof AnamnesesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comparacoes': typeof ComparacoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/montar-treino': typeof MontarTreinoRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/anamnese': typeof AlunoAnamneseRoute
  '/aluno/comparacao': typeof AlunoComparacaoRoute
  '/aluno/progresso': typeof AlunoProgressoRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/aluno/': typeof AlunoIndexRoute
  '/alunos/': typeof AlunosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/aluno'
    | '/alunos'
    | '/anamneses'
    | '/biblioteca'
    | '/comparacoes'
    | '/dashboard'
    | '/login'
    | '/montar-treino'
    | '/aluno/agenda'
    | '/aluno/anamnese'
    | '/aluno/comparacao'
    | '/aluno/progresso'
    | '/alunos/$studentId'
    | '/aluno/'
    | '/alunos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/anamneses'
    | '/biblioteca'
    | '/comparacoes'
    | '/dashboard'
    | '/login'
    | '/montar-treino'
    | '/aluno/agenda'
    | '/aluno/anamnese'
    | '/aluno/comparacao'
    | '/aluno/progresso'
    | '/alunos/$studentId'
    | '/aluno'
    | '/alunos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/aluno'
    | '/alunos'
    | '/anamneses'
    | '/biblioteca'
    | '/comparacoes'
    | '/dashboard'
    | '/login'
    | '/montar-treino'
    | '/aluno/agenda'
    | '/aluno/anamnese'
    | '/aluno/comparacao'
    | '/aluno/progresso'
    | '/alunos/$studentId'
    | '/aluno/'
    | '/alunos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  AlunosRoute: typeof AlunosRouteWithChildren
  AnamnesesRoute: typeof AnamnesesRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ComparacoesRoute: typeof ComparacoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MontarTreinoRoute: typeof MontarTreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/montar-treino': {
      id: '/montar-treino'
      path: '/montar-treino'
      fullPath: '/montar-treino'
      preLoaderRoute: typeof MontarTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparacoes': {
      id: '/comparacoes'
      path: '/comparacoes'
      fullPath: '/comparacoes'
      preLoaderRoute: typeof ComparacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamneses': {
      id: '/anamneses'
      path: '/anamneses'
      fullPath: '/anamneses'
      preLoaderRoute: typeof AnamnesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/alunos/$studentId': {
      id: '/alunos/$studentId'
      path: '/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AlunosStudentIdRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/aluno/progresso': {
      id: '/aluno/progresso'
      path: '/progresso'
      fullPath: '/aluno/progresso'
      preLoaderRoute: typeof AlunoProgressoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/comparacao': {
      id: '/aluno/comparacao'
      path: '/comparacao'
      fullPath: '/aluno/comparacao'
      preLoaderRoute: typeof AlunoComparacaoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/anamnese': {
      id: '/aluno/anamnese'
      path: '/anamnese'
      fullPath: '/aluno/anamnese'
      preLoaderRoute: typeof AlunoAnamneseRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/agenda': {
      id: '/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof AlunoRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoAnamneseRoute: typeof AlunoAnamneseRoute
  AlunoComparacaoRoute: typeof AlunoComparacaoRoute
  AlunoProgressoRoute: typeof AlunoProgressoRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoAnamneseRoute: AlunoAnamneseRoute,
  AlunoComparacaoRoute: AlunoComparacaoRoute,
  AlunoProgressoRoute: AlunoProgressoRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface AlunosRouteChildren {
  AlunosStudentIdRoute: typeof AlunosStudentIdRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosStudentIdRoute: AlunosStudentIdRoute,
  AlunosIndexRoute: AlunosIndexRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlunoRoute: AlunoRouteWithChildren,
  AlunosRoute: AlunosRouteWithChildren,
  AnamnesesRoute: AnamnesesRoute,
  BibliotecaRoute: BibliotecaRoute,
  ComparacoesRoute: ComparacoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MontarTreinoRoute: MontarTreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
