/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupAdminRouteImport } from './routes/signup_.admin'
import { Route as AlunosStudentIdRouteImport } from './routes/alunos_.$studentId'
import { Route as AlunoProgressoRouteImport } from './routes/aluno_.progresso'
import { Route as AlunoAgendaRouteImport } from './routes/aluno_.agenda'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAdminRoute = SignupAdminRouteImport.update({
  id: '/signup_/admin',
  path: '/signup/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosStudentIdRoute = AlunosStudentIdRouteImport.update({
  id: '/alunos_/$studentId',
  path: '/alunos/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoProgressoRoute = AlunoProgressoRouteImport.update({
  id: '/aluno_/progresso',
  path: '/aluno/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/aluno_/agenda',
  path: '/aluno/agenda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aluno': typeof AlunoRoute
  '/alunos': typeof AlunosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/progresso': typeof AlunoProgressoRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/signup/admin': typeof SignupAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aluno': typeof AlunoRoute
  '/alunos': typeof AlunosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/progresso': typeof AlunoProgressoRoute
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/signup/admin': typeof SignupAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/aluno': typeof AlunoRoute
  '/alunos': typeof AlunosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/aluno_/agenda': typeof AlunoAgendaRoute
  '/aluno_/progresso': typeof AlunoProgressoRoute
  '/alunos_/$studentId': typeof AlunosStudentIdRoute
  '/signup_/admin': typeof SignupAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/aluno'
    | '/alunos'
    | '/biblioteca'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/aluno/agenda'
    | '/aluno/progresso'
    | '/alunos/$studentId'
    | '/signup/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/aluno'
    | '/alunos'
    | '/biblioteca'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/aluno/agenda'
    | '/aluno/progresso'
    | '/alunos/$studentId'
    | '/signup/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/aluno'
    | '/alunos'
    | '/biblioteca'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/aluno_/agenda'
    | '/aluno_/progresso'
    | '/alunos_/$studentId'
    | '/signup_/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AlunoRoute: typeof AlunoRoute
  AlunosRoute: typeof AlunosRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoProgressoRoute: typeof AlunoProgressoRoute
  AlunosStudentIdRoute: typeof AlunosStudentIdRoute
  SignupAdminRoute: typeof SignupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/admin': {
      id: '/signup_/admin'
      path: '/signup/admin'
      fullPath: '/signup/admin'
      preLoaderRoute: typeof SignupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos_/$studentId': {
      id: '/alunos_/$studentId'
      path: '/alunos/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AlunosStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno_/progresso': {
      id: '/aluno_/progresso'
      path: '/aluno/progresso'
      fullPath: '/aluno/progresso'
      preLoaderRoute: typeof AlunoProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno_/agenda': {
      id: '/aluno_/agenda'
      path: '/aluno/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AlunoRoute: AlunoRoute,
  AlunosRoute: AlunosRoute,
  BibliotecaRoute: BibliotecaRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoProgressoRoute: AlunoProgressoRoute,
  AlunosStudentIdRoute: AlunosStudentIdRoute,
  SignupAdminRoute: SignupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
